variables:
  KNOWROB_MONGO_HOST: mongo
  KNOWROB_MONGO_PORT: 27017

default:
  image: jeremiasthun/knowrob-playground
  services:
    - name: mongo:4.4.9
      alias: mongo
  before_script:
    - PATH_TO_NEEM=$PWD
    - cd /home/validator/catkin_ws/src/knowrob
    - git pull
    - cd /home/validator/catkin_ws/src/neem_validator
    - git pull
    - catkin build
    - source /source_ros.sh

build-job:
  stage: build
  script:
    - cd /home/validator/catkin_ws/src/neem_validator/settings
    - 'echo - "Order: [FilesystemCheck]" > pipeline_workflow.yaml'
    - 'echo -e "- FilesystemCheck:\n  - {extension: .bson, fail_response: err, store_result_as: FOUND_BSONS}" >> pipeline_workflow.yaml'
    - roslaunch neem_validator validator.launch path_to_neem:=$PATH_TO_NEEM

